import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href={`/countries`}>
          <a>countries</a>
        </Link>
        <br />
        <Link href={`/issues`}>
          <a>issues</a>
        </Link>
        <br />
        <Link href={`/articles`}>
          <a>articles</a>
        </Link>
      </main>
    </>
  )
}

export default Home
